wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1669104372.291164
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 24
      4: 3.9.10
      5: 0.13.5
      8:
      - 5
agent_acceleration:
  desc: null
  value: 4.0
eval_num_episodes:
  desc: null
  value: 100
expr_name:
  desc: null
  value: test
predator_acceleration:
  desc: null
  value: 2.0
